config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index"
  get "add_data", to: "home#add_data"
  post "import_csv", to: "home#import_csv"

  resources :parliamentaries, only: %i[index show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parliamentary.rb
# frozen_string_literal: true

class Parliamentary < ApplicationRecord
  has_many :spendings
  has_one_attached :photo

  validates :name, :register, :party, presence: true

  validates :name, uniqueness: true

  def get_photo
    begin
      downloaded_photo = Down.download(
        "http://www.camara.leg.br/internet/deputado/bandep/#{self.register}.jpg"
      )
    rescue Down::NotFound
      return
    end

    self.photo.attach(
      io: downloaded_photo, filename: "#{self.name}.jpg"
    )
  end

  def spendings_sum
    spendings_sum = 0
    spendings = self.spendings

    spendings.each do |spending|
      spendings_sum += spending.value
    end

    spendings_sum
  end

  def most_expensive_spending
    value_list = []
    spendings = self.spendings

    spendings.each do |spending|
      value_list << spending.value
    end

    value_list.sort! { |x, y| y <=> x }
    value_list[0]
  end
end

app/models/repository.rb
# frozen_string_literal: true

class Repository
  class << self
    def import_parliamentaries(file)
      items = []
      names = []
      CSV.foreach(file, col_sep: ";", encoding: "bom|utf-8", quote_char: '"', headers: :first_row) do |row|
        attributes = row.to_h.deep_symbolize_keys

        if attributes[:sgUF] == "SP"
          parliamentary = attributes[:txNomeParlamentar]

          items << new_parliamentary(attributes) if names.exclude?(parliamentary)

          names << parliamentary
        end
      end
      Parliamentary.import(items)
    end

    def import_spendings(file)
      items = []
      last_name = ""
      parliamentary = ""
      CSV.foreach(file, col_sep: ";", encoding: "bom|utf-8", quote_char: '"', headers: :first_row) do |row|
        attributes = row.to_h.deep_symbolize_keys

        if attributes[:sgUF] == "SP"
          parliamentary_name = attributes[:txNomeParlamentar]

          if last_name != parliamentary_name
            parliamentary = Parliamentary.where(name: parliamentary_name).first
            last_name = parliamentary_name
          end

          spending = new_spending(attributes)

          spending.parliamentary = parliamentary
          items << spending
        end
      end
      Spending.import(items)
    end

    private
      def new_parliamentary(attributes)
        Parliamentary.new(
          name: attributes[:txNomeParlamentar],
          register: attributes[:ideCadastro],
          party: attributes[:sgPartido]
        )
      end

      def new_spending(attributes)
        Spending.new(
          description: attributes[:txtDescricao],
          provider: attributes[:txtFornecedor],
          date: attributes[:datEmissao],
          value: attributes[:vlrLiquido],
          document_url: attributes[:urlDocumento]
        )
      end
  end
end

app/models/spending.rb
# frozen_string_literal: true

class Spending < ApplicationRecord
  belongs_to :parliamentary

  validates :description, :provider, :date, :value,
            :document_url, presence: true

  validates :document_url, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  def add_data; end

  def import_csv
    begin
     @parliamentaries = Repository.import_parliamentaries(params[:file])

     @spendings = Repository.import_spendings(params[:file])
   rescue StandardError
     flash[:alert] = "N\u00E3o foi poss\u00EDvel adicionar as informa\u00E7\u00F5es"
     redirect_to :add_data
     return
   end

    redirect_to parliamentaries_path
  end
end

app/controllers/parliamentaries_controller.rb
# frozen_string_literal: true

class ParliamentariesController < ApplicationController
  def index
    @parliamentaries = Parliamentary.all
  end

  def show
    @parliamentary = Parliamentary.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/add_data.html.erb
<center>
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4" style="margin-top:75px" text-align="center">
      <div class="card">
        <div class="card-body">
          <%= form_tag import_csv_path, multipart: true do %>
          <%= file_field_tag :file%>
          <%= submit_tag "Importar CSV"%>
          <% end %>
        </div>
      </div>
      <p><%= flash[:alert] %></p>

      <button type="button" class="btn btn-primary" style="margin-top:75px" style="margin-bottom:25px">
        <%= link_to 'Voltar', root_path, style: 'color: white'%>
      </button>
      <div class="row">
      </div>
    </div>
  </div>
<center>

app/views/home/index.html.erb
<center>
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6" style="margin-top:75px">
      <h1><b>Desafio Backend</b></h1>

      <div style="margin-top:75px">  
        <p>    O projeto Despesas-Parlamentares é resultado de Desafio Backend da AgendaEdu,
               que consiste em importar as informações das despesas da Cota para o Exercício 
               da Atividade Parlamenta(CEAP) dos Deputados Federais, no caso de São Paulo, do 
               ano de 2019 para que possam ser vizualizadas de uma forma mais acessível, além 
               de incentivar a fiscalização dos gastos com dinheiro público, assim como a 
               disponibilização de dados abertos para consulta popular.
        </p>
      </div>
    </div>
  </div>
<center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Despesas Parlamentares</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Despesas Parlamentares</a>
      <form class="form-inline">
        <button class="btn btn-secondary" type="button"><%= link_to 'Parlamentares', parliamentaries_path, style: 'color: white'%></button>
        <div style="padding-left: 10px;">
          <button class="btn btn-secondary" type="button"><%= link_to 'Adicionar Despesas', add_data_path, style: 'color: white'%></button>
        </div>
      </form>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/parliamentaries/index.html.erb
<center>
  <div class="row">
    <div class="col-md-1">
    </div>
      <div class="col-md-10" style="margin-top:50px">

        <h1><b>Parlamentares</b></h1>

        <div class="row" style="margin-top:50px">
          <% @parliamentaries.each do |parliamentary| %>
            <div class="col-sm-2">
              <div class="card h-75" style="margin:0.5rem">
                <div class="card-body">
                    <h5 class="card-title"><%= link_to parliamentary.name, parliamentary %></h5>
                </div>
              </div>
            </div>
          <% end %>
        </div>

      <button type="button" class="btn btn-primary" style="margin-bottom:25px">
        <%= link_to 'Voltar', root_path, style: 'color: white'%>
      </button>
    </div>
  </div>
<center>

app/views/parliamentaries/show.html.erb
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-10">
    <div class="row">
      <div class="col-md-2" style="margin-top:25px">
        <%= image_tag "http://www.camara.leg.br/internet/deputado/bandep/#{@parliamentary.register}.jpg", size: "190x260"%>
      </div>
      <div class="col-md-4" style="margin-top:100px">
        <h1><b><%= @parliamentary.name%></b></h1>
        <h2>Partido: <%= @parliamentary.party%></h2>
      </div>
      <div class="col-md-6" style="margin-top:25px">
        <%= pie_chart @parliamentary.spendings.group(:description).count %>
      </div>
    </div>

    <center>
      <div class="row" style="margin-top:50px">
        <div class="col-md">
          <h3>Gastos totais em 2019: <b>R$ <%= sprintf('%.2f', @parliamentary.spendings_sum) %></b></h3>
        </div>
        <div class="col-md">
          <h3>Maior despesa do ano: <b>R$ <%= sprintf('%.2f', @parliamentary.most_expensive_spending) %></b></h3>
        </div>
      </div>
    </center>


    <div class="row" style="margin-top:50px">
      <table class="table">
        <thead>
          <tr>
            <th>Descrição</th>
            <th>Fornecedor</th>
            <th>Data de Emissão</th>
            <th>Valor Líquido</th>
            <th>Documento</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @parliamentary.spendings.order("date").each do |spending| %>
            <tr>
              <td><%= spending.description%></td>
              <td><%= spending.provider%></td>
              <td><%= spending.date.strftime("%d/%m/%Y")%></td>
              <td>R$ <%= sprintf('%.2f', spending.value)%></td>
              <td><%= link_to 'Nota Fiscal', spending.document_url, target: '_blank'%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
      <button type="button" class="btn btn-primary" style="margin-bottom:25px"><%= link_to 'Voltar', parliamentaries_path, style: 'color: white'%></button>
  </div>
</div>